version: '3.8'

services:
  client:
    build:
      context: ./client  # Путь к каталогу с проектом React
    ports:
      - "80:80"  # Доступ к фронтенду через порт 80
    depends_on:
      - server

  server:
    build:
      context: ./server  # Путь к каталогу с сервером Node.js
    ports:
      - "5000:5000"  # Доступ к серверу API через порт 5000
    environment:
      - DB_NAME=coffee
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=random_secret_key123

    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: coffee
    ports:
      - "5432:5432"  # Доступ к базе данных PostgreSQL через порт 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
