# Используем официальный образ Node.js
FROM node:18

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь проект
COPY . .

# Открываем порт для сервера
EXPOSE 5000

# Запускаем сервер с использованием команды npm run dev
CMD ["npm", "run", "dev"]
