export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ALLPRODUCTS_ROUTE = '/'
export const PRODUCT_ROUTE = '/product'
export const BASKET_ROUTE = '/basket'